export const AppRoutes = {
  home: '',
  signup: 'signup',
  signin: 'signin',
  forbidden: 'forbidden',
  profile: 'profile',
  sessions: 'sessions',
  sessionRoom: 'sessions/:code',
  game: 'sessions/:code/game',
  backgammonRules: 'backgammon-rules',
  backgammonHistory: 'backgammon-history',

  groups: 'groups',
  groupsAll: 'all',
  groupsMy: 'my',
  groupsJoinRequests: 'join-requests',
  groupsCreate: 'create',
  groupsDetails: ':groupId',
  groupsOverview: 'overview',
  groupsEdit: 'edit',
  groupsMembers: 'members',
  groupsRequests: 'requests',

  tournaments: 'tournaments',
  tournamentsAll: 'all',
  tournamentsMy: 'my',
  tournamentsJoinRequests: 'join-requests',
  tournamentsCreate: 'create',
  tournamentsDetails: ':tournamentId',
  tournamentsOverview: 'overview',
  tournamentsEdit: 'edit',
  tournamentsParticipants: 'participants',
  tournamentsRequests: 'requests',
} as const;
